[proxmox]
pve-01 ansible_host=192.168.1.50 ansible_user=root

[nodes]
rocky-base ansible_host=192.168.1.182 ansible_user=root
# thinkpad   ansible_host=192.168.1.X     ansible_user=root

[homelab:children]
proxmox
nodes

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args="-o StrictHostKeyChecking=no"
