---
- name: Manutenção Geral do Homelab
  hosts: homelab
  become: true

  tasks:
    - name: Atualizar repositórios e pacotes no Proxmox (Debian)
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        autoremove: true
      when: ansible_os_family == "Debian"

    - name: Atualizar todos os pacotes no Rocky Linux (RedHat)
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"